import React from 'react';
import './Products.css';

function Products() {
  const data = [
    {
      image: "https://5.imimg.com/data5/SELLER/Default/2022/7/IO/FK/GK/148254360/mild-steel-sand-filter-500x500.jpg",
      name: "SAND FILTERS",
      description: "Sand filtration is used for the removal of suspended matter, as well as floating and sinkable particles. The wastewater flows vertically through a fine bed of sand and/or gravel. Particles are removed by way of absorption or physical encapsulation."
      
    },
    {
      image: "https://5.imimg.com/data5/NB/VH/EL/SELLER-4315808/biogas-plant-250x250.jpg",
      name: "BIOGAS PLANTS",
      description: "Biogas can replace fossil and raw materials in a variety of industrial applications. Food waste and livestock manure are converted into biogas, a climate-friendly energy that can be used to heat buildings,etc. "
    
    },
    {
      image: "https://3.imimg.com/data3/EI/JH/MY-9867897/prefabricated-sewage-treatment-plant.jpg",
      name: "SEWAGE TREATMENT TANKS",
      description: "The principle of a Sewage Treatment Plant (STP) involves the treatment of wastewater through a series of physical, biological, and chemical processes to remove pollutants and contaminants."
    
    },
    {
      image: "https://aquashakti.com/wp-content/uploads/2022/07/Effluent-treatment-plant.jpg",
      name: "EFFLUENT TREATMENT TANKS",
      description: "An Industrial Effluent Treatment Plant (ETP) is a facility designed to treat wastewater generated by industrial activities, such as manufacturing, chemical processing, and food production."
    
    },
    {
      image: "https://d91ztqmtx7u1k.cloudfront.net/ClientContent/Images/Catalogue/20230622045220-995d8987-13c5-4893-9f7e-518890855948.jpg",
      name: "CARBON FILTERS",
      description: "Activated carbon filters are mainly used to treat small air flow rates and low concentrations of pollutants, to reduce odours and particular substances difficult to process such as silicates."
    
    },
    {
      image: "https://4.imimg.com/data4/LM/LH/MY-859767/customized-ss-storage-tanks-500x500.jpg",
      name: "STORAGE TANKS",
      description: "Storage tanks serve two major purposes. One is to provide storage volume and the other is to provide pressure to the distribution system. A particular tank can serve one or both purposes depending on its location within the system and its type of configuration."
    
    },
    {
      image: "https://5.imimg.com/data5/SELLER/Default/2022/9/LY/PG/LA/824918/demineralisation-plant-d-m-plant-500x500.jpg",
      name: "WATERWASTE TREATMENT PLANTS",
      description: "Industry generates significant wastewater which can pose environmental challenges if not treated properly. To mitigate these concerns, implementing a wastewater treatment plant is crucial for the steel industry. "
    
    }
  ];

  return (
    <div className='products'>
        <h1 className='title'>OUR PRODUCTS RANGE</h1>
          <div className='cards'>
        
        {data.map((elem, index) => (
          <div key={index} className='card-item'>
            {elem.image && <img src={elem.image} alt={elem.name} />}
            <h3 >{elem.name}</h3>
            <p>{elem.description}</p>
          </div>
        ))}
      </div>
    </div>
    
  );
}

export default Products;
